### PR TITLE
[#268][Security] Fix the dependabot alert

### LINKED ISSUE #268: [Security] Fix the dependabot alert
Remove vulnerable spark jar properties from logging module. For ref - https://github.com/paypal/gimel/security/dependabot/gimel-logging/gimel-logging_2.2/pom.xml/org.apache.spark:spark-core_2.11/open

Run the dependabot plugin.

There should not be any dependabot alerts

**Screenshots**

Remove the properties from gimel-logging_2.2 module 
<!--- If you are aware of a potential fix, please share the details.

### PR DESCRIPTION
**Pull request by Susheendar**
Make sure you have checked all steps below.

### GitHub Issue
Fixes #268 

### Checklist:

- [ ] This pull request updates the documentation
- [X] This pull request changes library dependencies
- [X] Title of the PR is of format (example) : [#25][Github] Add Pull Request Template

### What is the purpose of this pull request?
This pull request fixes the dependebot alerts.

### How was this change validated?
Ran dependabot plugin and verified the issues are not shown.

### Commit Guidelines
- [ ] My commits all reference GH issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by Dee-Pac** [comment]
Hi @Susheendar  - Do we need the 2.2 version of the logging module? I believe we can deprecate this version and retain the 2.3 version going forward.

**Comment by Susheendar** [comment]
Hi @Dee-Pac We can create an another feature request to deprecate and remove the module, It would take little time to remove all the dependencies of 2.2 , also we need to test it. For now, I hope this will fix the alert.

**Comment by Dee-Pac** [comment]
@Susheendar  Could you please share the test results of this change? Does the dependency removal cause any exceptions?

**Comment by Susheendar** [comment]
@Dee-Pac  This PR does not remove any dependency , just removed the properties in logging module 2.2 ,so that logging module can use parent project dependency versions.I have ran the build and it got succeeds.

**Review by Dee-Pac — APPROVED** [review]
Thanks for the clarification @Susheendar .

**Pull request merged**
