### PR TITLE
[#188] Add gimel-serde module

### LINKED ISSUE #188: [Enhancement] Decouple deserialization/serialization logic from gimel data apis
**What feature are your requesting?**
Decouple deserialization/serialization logic from gimel data apis

**What benefits do you foresee from the feature you are requesting?**
It enables pluggable deserialization/serialization logic while reading/writing from any storage through Gimel Data API

**Potential solution/ideas?**
Create a separate module for gimel-serde

**Additional context**

### PR DESCRIPTION
**Pull request by anishanainani**
Make sure you have checked all steps below.

### GitHub Issue
Fixes #188 

### Checklist:

- [x] This pull request updates the documentation
- [x] This pull request changes library dependencies
- [x] Title of the PR is of format (example) : [#25][Github] Add Pull Request Template

### What is the purpose of this pull request?
- Decouple deserialization/serialization logic from gimel data APIs
- It enables pluggable deserialization/serialization logic while reading/writing from any storage through Gimel Data API

### How was this change validated?
- Unit Tests
- Spark shell

##### Avro Deserializer
```
val dataset = com.paypal.gimel.DataSet(spark)
  
val options = Map("rest.service.method" -> "https",
"rest.service.host" -> "udc-rest-service-host",
"rest.service.port" -> "443",
"gimel.deserializer.avro.schema.url" -> "http://schema-registry-host:8081",
"gimel.deserializer.avro.schema.source" -> "CSR",
"gimel.deserializer.avro.schema.subject" -> "test_subject",
"gimel.deserializer.class" -> "com.paypal.gimel.deserializers.generic.AvroDeserializer")

val df = dataset.read("udc.Kafka.Gimel_Dev.default.test_avro_csr", options)
df.show
```

##### Json Dynamic Deserializer
```
val dataset = com.paypal.gimel.DataSet(spark)
  
val options = Map("rest.service.method" -> "https",
"rest.service.host" -> "udc-rest-service-host",
"rest.service.port" -> "443",
"gimel.deserializer.class" -> "com.paypal.gimel.deserializers.generic.JsonDynamicDeserializer")

val df = dataset.read("udc.Kafka.Gimel_Dev.default.test_json_dynamic", options)
df.show
```

### Commit Guidelines
- [x] My commits all reference GH issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by Dee-Pac** [comment]
@anishanainani Could you pls add the readme to demonstrate the usecases of SerDe?

**Comment by anishanainani** [comment]
> @anishanainani Could you pls add the readme to demonstrate the usecases of SerDe?

Added the doc. Please check out this page to see the rendered page https://github.com/anishanainani/gimel/blob/gimelserde/docs/gimel-serde/gimel-serde.md

**Comment by Dee-Pac** [comment]
@anishanainani Could you please rebase the POM. There is a conflict in the file since I merged the other PR for gimel-parser.

**Comment by anishanainani** [comment]
> @anishanainani Could you please rebase the POM? There is a conflict in the file since I merged the other PR for gimel-parser.

@Dee-Pac Done.

**Pull request merged**
